#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {PENCIL, ERASER, CIRCLE, TRIANGLE, RECTANGLE, POLYGON, MOUSE, DRAG, TO_FRONT, TO_BACK, BIG, SMALL};

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET, CUSTOM};

enum ACTION {NONE, CLEAR};

#endif